### ISSUE TITLE
Fix the web app install banner not popping up to  first time visitors.

### ISSUE THREAD

**Issue by osioke** [devcenter-square/disease-info-ui#23] opened 2016-10-04 11:10 UTC
Fix the web app install banner not popping up to first time visitors. If this is done, first time visitors to the site will be shown a banner in Chrome and Opera (and maybe other browsers) to install the web app on the mobile device.

**Comment by wiewioraseb** [comment] 2016-10-07 16:34
I could take this one, but I can't reproduce it :(

**Comment by yomete** [comment] 2016-10-07 16:49
Hi!
What do you mean you can't reproduce it?

**Comment by wiewioraseb** [comment] 2016-10-07 17:13
I can't see any banner on the page. I might not get it right, are we talking about some kind of a modal element poping up?

**Comment by yomete** [comment] 2016-10-07 20:04
No. This a repo for a Progressive Web App . 
We made it a Progressive Web App but we haven't been able to make it display the web app install banner.

https://developers.google.com/web/fundamentals/engage-and-retain/app-install-banners/

**Comment by WesleyKlop** [comment] 2016-10-07 20:56
This is impossible to show on the first visit because of this criteria (From https://developers.google.com/web/fundamentals/engage-and-retain/app-install-banners/#what_are_the_criteria) 

* Is visited at least twice, with at least five minutes between visits.

What you _could_ do is check if it's the user first visit and then show them a dialog suggesting them to install the website as an app though I wouldn't recommend that.

**Comment by osioke** [comment] 2016-10-20 12:25
Based on @WesleyKlop's comments, a test with [lighthouse](https://developers.google.com/web/tools/lighthouse/), and checking the repo, it would seem we do not have a [web app manifest file](https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/). Or do we? @yomete & @mykeels 

cc: @wiewioraseb

**Comment by mykeels** [comment] 2016-10-20 12:44
https://disease-info.herokuapp.com/assets/manifest.json

We do ^^

**Comment by osioke** [comment] 2016-10-20 14:26
Seen @mykeels, thanks. 

Chrome dev tools is saying _property 'scope' ignored. Start URL should be within the scope of scope URL._
![image](https://cloud.githubusercontent.com/assets/7646430/19563627/9f19e852-96d8-11e6-921e-55578db2e5f1.png)


Lighthouse is saying manifest does not exist.
![image](https://cloud.githubusercontent.com/assets/7646430/19563590/747bf3c4-96d8-11e6-8a79-99eeb35452e3.png)


I'm guessing these errors have something to do with the we app banner not showing.

@wiewioraseb @yomete @WesleyKlop @mykeels

**Comment by osioke** [comment] 2016-10-21 09:29
@ireade made a PR #44 which should/may help a bit

**Comment by juancuiule** [comment] 2016-10-27 02:07
I'm working on this...

**Comment by yomete** [comment] 2016-10-27 03:23
Fixed by PR #49

**Comment by yomete** [comment] 2016-10-27 03:57
Hey @juancuiule one more thing.
 Can you help check https://disease-info.herokuapp.com and see if the install web app banner pops up?

**Comment by juancuiule** [comment] 2016-10-27 04:09
Done.
![screenshot 01-05am oct 27 2016](https://cloud.githubusercontent.com/assets/12143451/19754226/fbd9ce96-9be1-11e6-936d-7769f3dcbc31.png)

Can you please check this question? https://github.com/devcenter-square/disease-info-ui/pull/49#issuecomment-256538737

**Closed** 2016-10-27 04:11 UTC
Labels: enhancement, hacktoberfest, help wanted
